import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Banner>
        <div className="page-banner-content">
              <ul className="breadcrumb">
                  <li><a href="#">Home</a></li>
                  <li className="active">Contact Us</li>
              </ul>
              <h2 className="title">Contact <span>Us</span></h2>
          </div>
      </Banner>


    </div>
  )
}
